### PR TITLE
Fix https://github.com/rubys/wunderbar/issues/11

### PR DESCRIPTION
**Pull request by sebbASF**
Existing code may be using two hashes for JSON and Text System methods.
If the code is unconditionally changed to use a single hash, such code will break as the BuilderClass only expects a single trailing hash.

This patch checks for two trailing hashes, and if so, keeps the existing code.

Otherwise, the single has is passed to the parent class.

### CODE REVIEW

**Comment by rubys** [comment]
looks like the test failures are unrelated, I'll investigate.  How urgently is this fix needed?

**Comment by sebbASF** [comment]
Not especially urgent as Whimsy can use two hashes.

**Comment by rubys** [comment]
Sorry for the delay.  I've fixed the test failures.  Can I trouble you to rebase this so that we can see if the tests pass?

**Comment by sebbASF** [comment]
Could not work out how to rebase it. The tests have run OK though, so maybe no more is needed?

**Pull request merged**
